# Generated by Django 4.2.7 on 2023-11-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userrole_userprofile_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('TRAINER', 'Trainer'), ('ADMIN', 'Admin')], max_length=50, unique=True),
        ),
    ]
